src/main/java/com/henriquelavor/sigpat/model/ConsultaReferenciasFornecedoresBean.java
package com.henriquelavor.sigpat.model;

import java.io.Serializable;
import java.util.List;

import javax.faces.application.FacesMessage;
import javax.faces.context.FacesContext;
import javax.faces.view.ViewScoped;
import javax.inject.Inject;
import javax.inject.Named;

import com.henriquelavor.sigpat.repository.ReferenciasFornecedores;
import com.henriquelavor.sigpat.service.CadastroReferenciasFornecedores;
import com.henriquelavor.sigpat.service.NegocioException;

/**
 * @author Henrique Lavor
 * @data 27.05.2016
 * @version 1.0
 */

@Named
@ViewScoped
public class ConsultaReferenciasFornecedoresBean implements Serializable {

	private static final long serialVersionUID = 1L;

	@Inject
	private ReferenciasFornecedores referenciasFornecedoresRepository;
	
	@Inject
	private CadastroReferenciasFornecedores cadastro;
	
	private List<ReferenciaFornecedor> referenciasFornecedores;
	
	private ReferenciaFornecedor referenciaFornecedorSelecionada;
	
	public void excluir() {
		FacesContext context = FacesContext.getCurrentInstance();

		try {
			this.cadastro.excluir(this.referenciaFornecedorSelecionada);
			this.consultar();

			context.addMessage(null, new FacesMessage(FacesMessage.SEVERITY_WARN,
					"Referência de Fornecedor excluída com sucesso!",null));
		} catch (NegocioException e) {
			FacesMessage mensagem = new FacesMessage(e.getMessage());
			mensagem.setSeverity(FacesMessage.SEVERITY_ERROR);
			context.addMessage(null, mensagem);
		}
	}

	
	public void consultar() {
		this.referenciasFornecedores = referenciasFornecedoresRepository.todas();
	}

	public List<ReferenciaFornecedor> getReferenciasFornecedores() {
		return referenciasFornecedores;
	}
	
	public List<ReferenciaFornecedor> getConsultar() {
		return referenciasFornecedores;
	}

	public ReferenciaFornecedor getReferenciaFornecedorSelecionada() {
		return referenciaFornecedorSelecionada;
	}
	
	public void setReferenciaFornecedorSelecionada(ReferenciaFornecedor referenciaFornecedorSelecionada) {
		this.referenciaFornecedorSelecionada = referenciaFornecedorSelecionada;
	}
}

src/main/java/com/henriquelavor/sigpat/model/ReferenciaFornecedor.java
package com.henriquelavor.sigpat.model;

import java.io.Serializable;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.EnumType;
import javax.persistence.Enumerated;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.validation.constraints.NotNull;
import javax.validation.constraints.Size;


/**
 * @author Henrique Lavor
 * @data 27.05.2016
 * @version 1.0
 */
@Entity
@Table (name="tb_referencia_fornecedor")
public class ReferenciaFornecedor implements Serializable {

	private static final long serialVersionUID = 1L;
	private Long codigoReferenciaFornecedor;
	private String descricaoReferenciaFornecedor;
	private RegraFornecedor regraFornecedor;
	
	@Id
	@GeneratedValue
	public Long getCodigoReferenciaFornecedor() {
		return codigoReferenciaFornecedor;
	}
	
	public void setCodigoReferenciaFornecedor(Long codigoReferenciaFornecedor) {
		this.codigoReferenciaFornecedor = codigoReferenciaFornecedor;
	}
	
	@NotNull
	@Size(max = 50)
	@Column(name = "descricao", length = 50, nullable = false)
	public String getDescricaoReferenciaFornecedor() {
		return descricaoReferenciaFornecedor;
	}
	public void setDescricaoReferenciaFornecedor(String descricaoReferenciaFornecedor) {
		this.descricaoReferenciaFornecedor = descricaoReferenciaFornecedor;
	}
	
	@NotNull
	@Enumerated(EnumType.STRING)
	@Column(nullable = false)
	public RegraFornecedor getRegraFornecedor() {
		return regraFornecedor;
	}

	public void setRegraFornecedor(RegraFornecedor regraFornecedor) {
		this.regraFornecedor = regraFornecedor;
	}

	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((codigoReferenciaFornecedor == null) ? 0 : codigoReferenciaFornecedor.hashCode());
		return result;
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj)
			return true;
		if (obj == null)
			return false;
		if (getClass() != obj.getClass())
			return false;
		ReferenciaFornecedor other = (ReferenciaFornecedor) obj;
		if (codigoReferenciaFornecedor == null) {
			if (other.codigoReferenciaFornecedor != null)
				return false;
		} else if (!codigoReferenciaFornecedor.equals(other.codigoReferenciaFornecedor))
			return false;
		return true;
	}
	
}

src/main/java/com/henriquelavor/sigpat/controller/CadastroReferenciaFornecedorBean.java
package com.henriquelavor.sigpat.controller;

import java.io.IOException;
import java.io.Serializable;
import java.util.List;

import javax.faces.application.FacesMessage;
import javax.faces.context.FacesContext;
import javax.faces.view.ViewScoped;
import javax.inject.Inject;
import javax.inject.Named;

import com.henriquelavor.sigpat.model.ReferenciaFornecedor;
import com.henriquelavor.sigpat.model.RegraFornecedor;
import com.henriquelavor.sigpat.repository.ReferenciasFornecedores;
import com.henriquelavor.sigpat.service.CadastroReferenciasFornecedores;
import com.henriquelavor.sigpat.service.NegocioException;

@Named
@ViewScoped
public class CadastroReferenciaFornecedorBean implements Serializable {

	private static final long serialVersionUID = 1L;

	@Inject
	private CadastroReferenciasFornecedores cadastro;

	@Inject
	private ReferenciasFornecedores referenciasFornecedores;

	private ReferenciaFornecedor referenciaFornecedor = new ReferenciaFornecedor();
	
	private List<ReferenciaFornecedor> todasReferenciasFornecedores;

	public void prepararCadastro() {
		this.todasReferenciasFornecedores = referenciasFornecedores.todas();
		if (this.referenciaFornecedor == null) {
			this.referenciaFornecedor = new ReferenciaFornecedor();
		}
	}

	public void salvar() throws IOException{
		FacesContext context = FacesContext.getCurrentInstance();
		try {
			this.cadastro.salvar(this.referenciaFornecedor);
			this.referenciaFornecedor = new ReferenciaFornecedor();
			context.addMessage(null, new FacesMessage("Registro Salvo com sucesso!"));
		} catch (NegocioException e) {
			FacesMessage mensagem = new FacesMessage(e.getMessage());
			mensagem.setSeverity(FacesMessage.SEVERITY_ERROR);
			context.addMessage(null, mensagem);
		}
	}

	public void editar() throws IOException {
		FacesContext context = FacesContext.getCurrentInstance();
		try {
			this.cadastro.editar(this.referenciaFornecedor);

			this.referenciaFornecedor = new ReferenciaFornecedor();
			context.addMessage(null, new FacesMessage(
					"Registro Atualizado com sucesso!"));
			FacesContext.getCurrentInstance().getExternalContext()
			.redirect("/sigpat/paginas/ReferenciaFornecedor/ConsultaReferenciasFornecedores.xhtml");
		} catch (NegocioException e) {
			FacesMessage mensagem = new FacesMessage(e.getMessage());
			mensagem.setSeverity(FacesMessage.SEVERITY_ERROR);
			context.addMessage(null, mensagem);
		}
	}
	
	public RegraFornecedor[] getRegrasForncedores() {
		return RegraFornecedor.values();
	}
	public List<ReferenciaFornecedor> getTodasReferenciasFornecedores() {
		return this.todasReferenciasFornecedores;
	}

	public ReferenciaFornecedor getReferenciaFornecedor() {
		return referenciaFornecedor;
	}

	public void setReferenciaFornecedor(ReferenciaFornecedor referenciaFornecedor) {
		this.referenciaFornecedor = referenciaFornecedor;
	}
}

src/main/webapp/paginas/ReferenciaFornecedor/CadastroReferenciaFornecedor.xhtml
<!DOCTYPE html>
<ui:composition template="/WEB-INF/template.xhtml"
	xmlns="http://www.w3.org/1999/xhtml"
	xmlns:f="http://xmlns.jcp.org/jsf/core"
	xmlns:h="http://xmlns.jcp.org/jsf/html"
	xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
	xmlns:p="http://primefaces.org/ui" xmlns:o="http://omnifaces.org/ui">

	<f:metadata>
		<o:viewParam name="codigoReferenciaFornecedor"
			value="#{cadastroReferenciaFornecedorBean.referenciaFornecedor}" />
		<f:viewAction
			action="#{cadastroReferenciaFornecedorBean.prepararCadastro}" />
	</f:metadata>

	<ui:define name="titulo">Cadastro de Referências de Fornecedores</ui:define>

	<ui:define name="content">
		<div class="ui-g ui-fluid">
			<div class="ui-g-12">
				<div class="card">
					<h1>
						<h:graphicImage library="lavor" name="referenciafornecedores.png"
							height="45" width="45" />
						Cadastro de Referências de Fornecedores <a href="../../dashboard.xhtml"><h:graphicImage library="lavor"
								name="voltar.gif" height="35" width="80" style="float:right;" />
						</a>
					</h1>

					<h:form id="frm">
						<p:messages showDetail="false" showSummary="true"
							autoUpdate="true" />

						<p:panel header="Cadastro de Referências de Fornecedores">
							<p:panelGrid columns="2" styleClass="semBorda">
								<p:outputLabel value="Nome da Referência do Fornecedor">
									<p:outputLabel value="*" style="font-size:11px; color:red;" />
									<h:graphicImage library="lavor" name="ajuda.png" height="15"
										width="15" style="float:right;" onclick="PF('dlg1').show();" />
								</p:outputLabel>
								<p:inputText size="70" required="true"
									value="#{cadastroReferenciaFornecedorBean.referenciaFornecedor.descricaoReferenciaFornecedor}"
									label="Nome da Referência do Fornecedor" immediate="true"
									maxlength="50"
									placeholder="informe o nome da referência do fornecedor"
									title="Informe o nome da Referência do Fornecedor." />

								<p:outputLabel value="Regra/Restrição" for="regraFornecedor">
									<p:outputLabel value="*" style="font-size:11px; color:red;" />
									<h:graphicImage library="lavor" name="ajuda.png" height="15"
										width="15" style="float:right;" onclick="PF('dlg2').show();" />
								</p:outputLabel>
								<p:selectOneMenu
									value="#{cadastroReferenciaFornecedorBean.referenciaFornecedor.regraFornecedor}"
									label="Regra/Restrição" id="regraFornecedor"
									filterMatchMode="contains">
									<f:selectItem itemLabel="Selecione" noSelectionOption="true" />
									<f:selectItems
										value="#{cadastroReferenciaFornecedorBean.regrasForncedores}"
										var="regraFornecedor" itemValue="#{regraFornecedor}"
										itemLabel="#{regraFornecedor}" />
								</p:selectOneMenu>
								<p:outputLabel />
								<p:outputLabel value=" * é campo de preenchimento obrigatório"
									style="font-size:11px; color:red;" />
								<p:commandButton value="Salvar"
									action="#{cadastroReferenciaFornecedorBean.salvar}"
									icon="ui-icon-save" process="@form" update="@form" style="width:100px"/>
							</p:panelGrid>
						</p:panel>
					</h:form>
					<p:dialog header="Ajuda: Nome da Referência do Fornecedor"
						widgetVar="dlg1" showEffect="explode" width="600" height="90"
						resizable="false" maximizable="false" position="center"
						hideEffect="explode">
						<h:outputText
							value="É a descrição do nome da Referência do Fornecedor, relativo ao fornecimento dos Bens." />
						<br />
						<br />
						<h:outputText value="Por exemplo: Ótimo Fornecedor" />
						<br />
						<div align="center">
							<p:button value="OK" icon="ui-icon-check"
								onclick="PF('dlg1').hide(); return false" style="width:100px"/>
						</div>
					</p:dialog>

					<p:dialog header="Ajuda: Regra/Restrição" widgetVar="dlg2"
						showEffect="explode" width="600" height="100" resizable="false"
						maximizable="false" position="center" hideEffect="explode">
						<h:outputText
							value="Para cada Referência de Fornecedor é possível associar as regras: Liberado ou Bloqueado." />
						<br />
						<br />
						<h:outputText
							value="Por exemplo: Lista Negra, poderia usar a regra/restrição BLOQUEADO, para alertar que existem Fornecedores inaptos!" />
						<br />
						<div align="center">
							<p:button value="OK" icon="ui-icon-check"
								onclick="PF('dlg2').hide(); return false" style="width:100px"/>
						</div>
					</p:dialog>
				</div>
			</div>
		</div>
	</ui:define>
</ui:composition>

src/main/webapp/paginas/ReferenciaFornecedor/CadastroReferenciaFornecedorEdit.xhtml
<!DOCTYPE html>
<ui:composition template="/WEB-INF/template.xhtml"
	xmlns="http://www.w3.org/1999/xhtml"
	xmlns:f="http://xmlns.jcp.org/jsf/core"
	xmlns:h="http://xmlns.jcp.org/jsf/html"
	xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
	xmlns:p="http://primefaces.org/ui" xmlns:o="http://omnifaces.org/ui">

	<f:metadata>
		<o:viewParam name="codigoReferenciaFornecedor"
			value="#{cadastroReferenciaFornecedorBean.referenciaFornecedor}" />
		<f:viewAction
			action="#{cadastroReferenciaFornecedorBean.prepararCadastro}" />
	</f:metadata>

	<ui:define name="titulo">Cadastro de Referências de Fornecedores</ui:define>

	<ui:define name="content">
		<div class="ui-g ui-fluid">
			<div class="ui-g-12">
				<div class="card">
					<h1>
						<h:graphicImage library="lavor" name="referenciafornecedores.png"
							height="45" width="45" />
						(ATUALIZANDO) Cadastro de Referências de Fornecedores <a
							href="ConsultaReferenciasFornecedores.xhtml"><h:graphicImage
								library="lavor" name="voltar.gif" height="35" width="80"
								style="float:right;" /> </a>
					</h1>

					<h:form id="frm">
						<p:messages showDetail="false" showSummary="true"
							autoUpdate="true" />

						<p:panel header="Cadastro de Referências de Fornecedores">
							<p:panelGrid columns="2" styleClass="semBorda">
								<p:outputLabel value="Nome da Referência do Fornecedor">
									<p:outputLabel value="*" style="font-size:11px; color:red;" />
									<h:graphicImage library="lavor" name="ajuda.png" height="15"
										width="15" style="float:right;" onclick="PF('dlg1').show();" />
								</p:outputLabel>
								<p:inputText size="70" required="true"
									value="#{cadastroReferenciaFornecedorBean.referenciaFornecedor.descricaoReferenciaFornecedor}"
									label="Nome da Referência do Fornecedor" immediate="true"
									maxlength="50"
									placeholder="informe o nome da referência do fornecedor"
									title="Informe o nome da Referência do Fornecedor." />

								<p:outputLabel value="Regra/Restrição" for="regraFornecedor">
									<p:outputLabel value="*" style="font-size:11px; color:red;" />
									<h:graphicImage library="lavor" name="ajuda.png" height="15"
										width="15" style="float:right;" onclick="PF('dlg2').show();" />
								</p:outputLabel>
								<p:selectOneMenu
									value="#{cadastroReferenciaFornecedorBean.referenciaFornecedor.regraFornecedor}"
									label="Regra/Restrição" id="regraFornecedor"
									filterMatchMode="contains">
									<f:selectItem itemLabel="Selecione" noSelectionOption="true" />
									<f:selectItems
										value="#{cadastroReferenciaFornecedorBean.regrasForncedores}"
										var="regraFornecedor" itemValue="#{regraFornecedor}"
										itemLabel="#{regraFornecedor}" />
								</p:selectOneMenu>
								<p:outputLabel />
								<p:outputLabel value=" * é campo de preenchimento obrigatório"
									style="font-size:11px; color:red;" />
								<p:commandButton value="Salvar"
									action="#{cadastroReferenciaFornecedorBean.editar}"
									icon="ui-icon-save" process="@form" update="@form" style="width:100px"/>
							</p:panelGrid>
						</p:panel>
					</h:form>
					<p:dialog header="Ajuda: Nome da Referência do Fornecedor"
						widgetVar="dlg1" showEffect="explode" width="600" height="90"
						resizable="false" maximizable="false" position="center"
						hideEffect="explode">
						<h:outputText
							value="É a descrição do nome da Referência do Fornecedor, relativo ao fornecimento dos Bens." />
						<br />
						<br />
						<h:outputText value="Por exemplo: Ótimo Fornecedor" />
						<br />
						<div align="center">
							<p:button value="OK" icon="ui-icon-check"
								onclick="PF('dlg1').hide(); return false" style="width:100px"/>
						</div>
					</p:dialog>

					<p:dialog header="Ajuda: Regra/Restrição" widgetVar="dlg2"
						showEffect="explode" width="600" height="100" resizable="false"
						maximizable="false" position="center" hideEffect="explode">
						<h:outputText
							value="Para cada Referência de Fornecedor é possível associar as regras: Liberado ou Bloqueado." />
						<br />
						<br />
						<h:outputText
							value="Por exemplo: Lista Negra, poderia usar a regra/restrição BLOQUEADO, para alertar que existem Fornecedores inaptos!" />
						<br />
						<div align="center">
							<p:button value="OK" icon="ui-icon-check"
								onclick="PF('dlg2').hide(); return false" style="width:100px" />
						</div>
					</p:dialog>
				</div>
			</div>
		</div>
	</ui:define>
</ui:composition>

src/main/webapp/paginas/ReferenciaFornecedor/ConsultaReferenciasFornecedores.xhtml
<!DOCTYPE html>
<ui:composition template="/WEB-INF/template.xhtml"
	xmlns="http://www.w3.org/1999/xhtml"
	xmlns:f="http://xmlns.jcp.org/jsf/core"
	xmlns:h="http://xmlns.jcp.org/jsf/html"
	xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
	xmlns:p="http://primefaces.org/ui">

	<f:metadata>
		<f:viewAction
			action="#{consultaReferenciasFornecedoresBean.consultar}" />
	</f:metadata>

	<ui:define name="titulo">Consulta de Referências de Fornecedores</ui:define>

	<ui:define name="content">
		<div class="ui-g ui-fluid">
			<div class="ui-g-12">
				<div class="card">
					<!-- Estilo usado para  -->
					<style type="text/css">
.colored {
	background-color: #000000;
	color: #FFFFFF;
}
</style>
					<h1>
						<h:graphicImage library="lavor" name="referenciafornecedores.png"
							height="45" width="45" />
						Consulta de Referências de Fornecedores <a
							href="../../dashboard.xhtml"><h:graphicImage library="lavor"
								name="voltar.gif" height="35" width="80" style="float:right;" />
						</a>
					</h1>

					<h:form id="frm">
						<p:messages showDetail="false" showSummary="true"
							autoUpdate="true" />

						<!-- 	<p:dataTable
				value="#{consultaReferenciasFornecedoresBean.referenciasFornecedores}"
				var="referenciasFornecedores" border="1" cellspacing="0"
				cellpadding="2" paginator="true" rows="10"
				paginatorPosition="bottom" id="tabela"
				emptyMessage="Não foi localizado o registro solicitado."
				rowStyleClass="#{referenciasFornecedores.regraFornecedor le 'Bloqueado' ? 'colored' : null}"> -->
						<p:dataTable
							value="#{consultaReferenciasFornecedoresBean.referenciasFornecedores}"
							expandableRowGroups="true" reflow="true" selectionMode="single"
							selection="#{consultaReferenciasFornecedoresBean.referenciaFornecedorSelecionada}"
							rowKey="#{referenciasFornecedores.codigoReferenciaFornecedor}"
							var="referenciasFornecedores" border="1" cellspacing="0"
							cellpadding="2" paginator="true"
							rowsPerPageTemplate="8,25,50,100" rows="8"
							paginatorPosition="bottom" id="tabela"
							emptyMessage="Não foi localizado o registro solicitado."
							paginatorTemplate="{CurrentPageReport}  {FirstPageLink} {PreviousPageLink} {PageLinks} {NextPageLink} {LastPageLink} {RowsPerPageDropdown}"
							currentPageReportTemplate="Total de {totalRecords} registros localizados - Página: {currentPage} de {totalPages}">

							<f:facet name="header">
       				 Lista de Referências de Fornecedores
					<div align="right">
									<p:commandButton id="toggler" type="button"
										value="Ajuste Colunas" icon="ui-icon-calculator" />
								</div>
								<p:columnToggler datasource="tabela" trigger="toggler" />
							</f:facet>

							<f:facet name="footer">
								<div align="right">
									Exportar
									<h:commandLink>
										<h:graphicImage library="lavor" name="pdf.png" width="20"
											title="Exportar para PDF" />
										<p:dataExporter type="pdf" target="tabela"
											fileName="referenciasfornecedores" />
									</h:commandLink>

									<h:commandLink>
										<h:graphicImage library="lavor" name="xls.png" width="20"
											title="Exportar para XLS" />
										<p:dataExporter type="xls" target="tabela"
											fileName="referenciasfornecedores" />
									</h:commandLink>

									<h:commandLink>
										<h:graphicImage library="lavor" name="xml.png" width="20"
											title="Exportar para XML" />
										<p:dataExporter type="xml" target="tabela"
											fileName="referenciasfornecedores" />
									</h:commandLink>
								</div>
							</f:facet>

							<p:column headerText="Nome da Referência do Fornecedor"
								style="width:30%"
								sortBy="#{referenciasFornecedores.descricaoReferenciaFornecedor}"
								filterBy="#{referenciasFornecedores.descricaoReferenciaFornecedor}"
								filterMatchMode="contains" id="camporefenciafornecedor">
								<h:outputText
									value="#{referenciasFornecedores.descricaoReferenciaFornecedor}" />
							</p:column>

							<p:column headerText="Regra/Restrição"
								style="width:10%;text-align: center"
								sortBy="#{referenciasFornecedores.regraFornecedor}"
								filterBy="#{referenciasFornecedores.regraFornecedor}"
								filterMatchMode="contains" id="campooregrafornecedor">
								<h:outputText value="#{referenciasFornecedores.regraFornecedor}" />
							</p:column>

							<p:column headerText="Ação" style="width:7%" exportable="false">
								<div align="center">
									<p:column style="width:20px">
										<p:commandButton update=":frm:referenciaFornecedorDetalhes" styleClass="blue-grey-btn"
											oncomplete="PF('dlgver').show()" icon="ui-icon-search"
											title="Ver">
											<f:setPropertyActionListener
												value="#{referenciasFornecedores}"
												target="#{consultaReferenciasFornecedoresBean.referenciaFornecedorSelecionada}" />
										</p:commandButton>
									</p:column>
									<p:column style="width:20px">
										<p:button icon="ui-icon-pencil" title="Alterar"
										    rendered="#{seguranca.autoridades=='[ROLE_ADMINISTRADORES]'}"
											outcome="/paginas/ReferenciaFornecedor/CadastroReferenciaFornecedorEdit">
											<f:param name="codigoReferenciaFornecedor"
												value="#{referenciasFornecedores.codigoReferenciaFornecedor}" />
										</p:button>
									</p:column>
									<p:column style="width:20px">
										<p:commandButton icon="ui-icon-trash" title="Excluir" styleClass="red-btn"
										    rendered="#{seguranca.autoridades=='[ROLE_ADMINISTRADORES]'}"
											process="@this" update="@form"
											action="#{consultaReferenciasFornecedoresBean.excluir}">
											<p:confirm header="Excluindo..."
												message="Tem certeza que deseja excluir este Registro?"
												icon="ui-icon-alert" />
											<f:setPropertyActionListener
												value="#{referenciasFornecedores}"
												target="#{consultaReferenciasFornecedoresBean.referenciaFornecedorSelecionada}" />
										</p:commandButton>
									</p:column>
								</div>
							</p:column>
						</p:dataTable>
						<p:dialog header="Detalhes: Referência de Fornecedor "
							widgetVar="dlgver" modal="true" showEffect="fade"
							hideEffect="fade" resizable="false">
							<p:outputPanel id="referenciaFornecedorDetalhes"
								style="text-align:center;">
								<p:panelGrid columns="2"
									rendered="#{not empty consultaReferenciasFornecedoresBean.referenciaFornecedorSelecionada}"
									columnClasses="label,value">

									<h:outputText value="Código Interno" style="font-weight:bold" />
									<h:outputText
										value="#{consultaReferenciasFornecedoresBean.referenciaFornecedorSelecionada.codigoReferenciaFornecedor}"
										style="font-weight:bold" />

									<h:outputText value="Nome da Referência do Fornecedor"
										style="font-weight:bold" />
									<h:outputText
										value="#{consultaReferenciasFornecedoresBean.referenciaFornecedorSelecionada.descricaoReferenciaFornecedor}"
										style="font-weight:bold" />

									<h:outputText value="Regra/Restrição" />
									<h:outputText
										value="#{consultaReferenciasFornecedoresBean.referenciaFornecedorSelecionada.regraFornecedor}" />
								</p:panelGrid>
							</p:outputPanel>
							<br />
							<div align="center">
								<p:button value="OK" icon="ui-icon-check"
									onclick="PF('dlgver').hide(); return false" style="width:100px"/>
							</div>
						</p:dialog>
					</h:form>
				</div>
			</div>
		</div>
	</ui:define>
</ui:composition>