src/main/java/com/henriquelavor/sigpat/model/ConsultaTiposInstituicoesBean.java
package com.henriquelavor.sigpat.model;

import java.io.Serializable;
import java.util.List;

import javax.faces.application.FacesMessage;
import javax.faces.context.FacesContext;
import javax.faces.view.ViewScoped;
import javax.inject.Inject;
import javax.inject.Named;

import com.henriquelavor.sigpat.repository.TiposInstituicoes;
import com.henriquelavor.sigpat.service.CadastroTiposInstituicoes;
import com.henriquelavor.sigpat.service.NegocioException;

/**
 * @author Henrique Lavor
 * @data 23.05.2016
 * @version 1.0
 */

@Named
@ViewScoped
public class ConsultaTiposInstituicoesBean implements Serializable {

	private static final long serialVersionUID = 1L;

	@Inject
	private TiposInstituicoes tiposInstituicoesRepository;
	
	@Inject
	private CadastroTiposInstituicoes cadastro;
	
	private List<TipoInstituicao> tiposInstituicoes;
	
	private TipoInstituicao tipoInstituicaoSelecionado;
	
	public void excluir() {
		FacesContext context = FacesContext.getCurrentInstance();

		try {
			this.cadastro.excluir(this.tipoInstituicaoSelecionado);
			this.consultar();

			context.addMessage(null, new FacesMessage(FacesMessage.SEVERITY_WARN,
					"Tipo de Instituição excluído com sucesso!",null));

		} catch (NegocioException e) {
			FacesMessage mensagem = new FacesMessage(e.getMessage());
			mensagem.setSeverity(FacesMessage.SEVERITY_ERROR);
			context.addMessage(null, mensagem);
		}
	}

	
	public void consultar() {
		this.tiposInstituicoes = tiposInstituicoesRepository.todos();
	}

	public List<TipoInstituicao> getTiposIntituicoes() {
		return tiposInstituicoes;
	}
	
	public List<TipoInstituicao> getConsultar() {
		return tiposInstituicoes;
	}

	public TipoInstituicao getTipoInstituicaoSelecionado() {
		return tipoInstituicaoSelecionado;
	}
	
	public void setTipoInstituicaoSelecionado(TipoInstituicao tipoInstituicaoSelecionado) {
		this.tipoInstituicaoSelecionado = tipoInstituicaoSelecionado;
	}
}

src/main/java/com/henriquelavor/sigpat/model/TipoInstituicao.java
package com.henriquelavor.sigpat.model;

import java.io.Serializable;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.validation.constraints.NotNull;
import javax.validation.constraints.Size;


/**
 * @author Henrique Lavor
 * @data 23.05.2016
 * @version 1.0
 */
@Entity
@Table (name="tb_tipo_instituicao")
public class TipoInstituicao implements Serializable {

	private static final long serialVersionUID = 1L;
	private Long codigoTipoInstituicao;
	private String descricaoTipoInstituicao;
	
	@Id
	@GeneratedValue
	public Long getCodigoTipoInstituicao() {
		return codigoTipoInstituicao;
	}
	public void setCodigoTipoInstituicao(Long codigoTipoInstituicao) {
		this.codigoTipoInstituicao = codigoTipoInstituicao;
	}
	
	@NotNull
	@Size(max = 100)
	@Column(name = "descricao", length = 100, nullable = false)
	public String getDescricaoTipoInstituicao() {
		return descricaoTipoInstituicao;
	}
	public void setDescricaoTipoInstituicao(String descricaoTipoInstituicao) {
		this.descricaoTipoInstituicao = descricaoTipoInstituicao;
	}
	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((codigoTipoInstituicao == null) ? 0 : codigoTipoInstituicao.hashCode());
		return result;
	}
	@Override
	public boolean equals(Object obj) {
		if (this == obj)
			return true;
		if (obj == null)
			return false;
		if (getClass() != obj.getClass())
			return false;
		TipoInstituicao other = (TipoInstituicao) obj;
		if (codigoTipoInstituicao == null) {
			if (other.codigoTipoInstituicao != null)
				return false;
		} else if (!codigoTipoInstituicao.equals(other.codigoTipoInstituicao))
			return false;
		return true;
	}
}

src/main/java/com/henriquelavor/sigpat/controller/CadastroTipoInstituicaoBean.java
package com.henriquelavor.sigpat.controller;

import java.io.IOException;
import java.io.Serializable;
import java.util.List;

import javax.faces.application.FacesMessage;
import javax.faces.context.FacesContext;
import javax.faces.view.ViewScoped;
import javax.inject.Inject;
import javax.inject.Named;

import com.henriquelavor.sigpat.model.TipoInstituicao;
import com.henriquelavor.sigpat.repository.TiposInstituicoes;
import com.henriquelavor.sigpat.service.CadastroTiposInstituicoes;
import com.henriquelavor.sigpat.service.NegocioException;

@Named
@ViewScoped
public class CadastroTipoInstituicaoBean implements Serializable {

	private static final long serialVersionUID = 1L;

	@Inject
	private CadastroTiposInstituicoes cadastro;

	@Inject
	private TiposInstituicoes tiposInstituicoes;

	private TipoInstituicao tipoInstituicao = new TipoInstituicao();
	
	private List<TipoInstituicao> todosTiposInstituicoes;

	public void prepararCadastro() {
		this.todosTiposInstituicoes = tiposInstituicoes.todos();
		if (this.tipoInstituicao == null) {
			this.tipoInstituicao = new TipoInstituicao();
		}
	}

	public void salvar() throws IOException{
		FacesContext context = FacesContext.getCurrentInstance();
		try {
			this.cadastro.salvar(this.tipoInstituicao);
			this.tipoInstituicao = new TipoInstituicao();
			context.addMessage(null, new FacesMessage("Registro Salvo com sucesso!"));
		} catch (NegocioException e) {
			FacesMessage mensagem = new FacesMessage(e.getMessage());
			mensagem.setSeverity(FacesMessage.SEVERITY_ERROR);
			context.addMessage(null, mensagem);
		}
	}

	public void editar() throws IOException {
		FacesContext context = FacesContext.getCurrentInstance();
		try {
			this.cadastro.editar(this.tipoInstituicao);

			this.tipoInstituicao = new TipoInstituicao();
			context.addMessage(null, new FacesMessage(
					"Registro Atualizado com sucesso!"));
			FacesContext.getCurrentInstance().getExternalContext()
			.redirect("/sigpat/paginas/TipoInstituicao/ConsultaTiposInstituicoes.xhtml");
		} catch (NegocioException e) {
			FacesMessage mensagem = new FacesMessage(e.getMessage());
			mensagem.setSeverity(FacesMessage.SEVERITY_ERROR);
			context.addMessage(null, mensagem);
		}
	}
	
	public List<TipoInstituicao> getTodosTiposInstituicoes() {
		return this.todosTiposInstituicoes;
	}

	public TipoInstituicao getTipoInstituicao() {
		return tipoInstituicao;
	}

	public void setTipoInstituicao(TipoInstituicao tipoInstituicao) {
		this.tipoInstituicao = tipoInstituicao;
	}
}

src/main/webapp/paginas/TipoInstituicao/CadastroTipoInstituicao.xhtml
<!DOCTYPE html>
<ui:composition template="/WEB-INF/template.xhtml"
	xmlns="http://www.w3.org/1999/xhtml"
	xmlns:f="http://xmlns.jcp.org/jsf/core"
	xmlns:h="http://xmlns.jcp.org/jsf/html"
	xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
	xmlns:p="http://primefaces.org/ui" xmlns:o="http://omnifaces.org/ui">

	<f:metadata>
		<o:viewParam name="codigoTipoInstituicao"
			value="#{cadastroTipoInstituicaoBean.tipoInstituicao}" />
		<f:viewAction action="#{cadastroTipoInstituicaoBean.prepararCadastro}" />
	</f:metadata>

	<ui:define name="titulo">Cadastro de Tipos de Instituições</ui:define>

	<ui:define name="content">
		<div class="ui-g ui-fluid">
			<div class="ui-g-12">
				<div class="card">
					<h1>
						<h:graphicImage library="lavor" name="tipoinstituicao.png"
							height="45" width="45" />
						Cadastro de Tipos de Instituições <a href="../../dashboard.xhtml"><h:graphicImage
								library="lavor" name="voltar.gif" height="35" width="80"
								style="float:right;" /> </a>
					</h1>

					<h:form id="frm">
						<p:messages showDetail="false" showSummary="true"
							autoUpdate="true" />

						<p:panel header="Cadastro de Tipos de Instituições">
							<p:panelGrid columns="2" styleClass="semBorda">
								<p:outputLabel value="Nome do Tipo de Instituição">
									<p:outputLabel value="*" style="font-size:11px; color:red;" />
									<h:graphicImage library="lavor" name="ajuda.png" height="15"
										width="15" style="float:right;" onclick="PF('dlg1').show();" />
								</p:outputLabel>
								<p:inputText size="100" required="true"
									value="#{cadastroTipoInstituicaoBean.tipoInstituicao.descricaoTipoInstituicao}"
									label="Nome do Tipo de Instituição" immediate="true"
									maxlength="100"
									placeholder="informe o nome do Tipo de Instituição"
									title="Informe o nome do Tipo de Instituição." />

								<p:outputLabel />
								<p:outputLabel value=" * é campo de preenchimento obrigatório"
									style="font-size:11px; color:red;" />
								<p:commandButton value="Salvar"
									action="#{cadastroTipoInstituicaoBean.salvar}"
									icon="ui-icon-save" process="@form" update="@form" style="width:100px" />
							</p:panelGrid>
						</p:panel>
					</h:form>
					<p:dialog header="Ajuda: Nome do Tipo de Instituição"
						widgetVar="dlg1" showEffect="explode" width="600" height="90"
						resizable="false" maximizable="false" position="center"
						hideEffect="explode">
						<h:outputText
							value="É a descrição do nome do Tipo de uma Instituição(Órgão)." />
						<br />
						<br />
						<h:outputText value="Por exemplo: Administração Direta" />
						<br />
						<div align="center">
							<p:button value="OK" icon="ui-icon-check"
								onclick="PF('dlg1').hide(); return false" style="width:100px"/>
						</div>
					</p:dialog>
				</div>
			</div>
		</div>
	</ui:define>
</ui:composition>

src/main/webapp/paginas/TipoInstituicao/CadastroTipoInstituicaoEdit.xhtml
<!DOCTYPE html>
<ui:composition template="/WEB-INF/template.xhtml"
	xmlns="http://www.w3.org/1999/xhtml"
	xmlns:f="http://xmlns.jcp.org/jsf/core"
	xmlns:h="http://xmlns.jcp.org/jsf/html"
	xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
	xmlns:p="http://primefaces.org/ui" xmlns:o="http://omnifaces.org/ui">

	<f:metadata>
		<o:viewParam name="codigoTipoInstituicao"
			value="#{cadastroTipoInstituicaoBean.tipoInstituicao}" />
		<f:viewAction action="#{cadastroTipoInstituicaoBean.prepararCadastro}" />
	</f:metadata>

	<ui:define name="titulo">Cadastro de Tipos de Instituições</ui:define>

	<ui:define name="content">
		<div class="ui-g ui-fluid">
			<div class="ui-g-12">
				<div class="card">
					<h1>
						<h:graphicImage library="lavor" name="tipoinstituicao.png"
							height="45" width="45" />
						(ATUALIZANDO) Cadastro de Tipos de Instituições <a
							href="ConsultaTiposInstituicoes.xhtml"><h:graphicImage
								library="lavor" name="voltar.gif" height="35" width="80"
								style="float:right;" /></a>
					</h1>

					<h:form id="frm">
						<p:messages showDetail="false" showSummary="true"
							autoUpdate="true" />

						<p:panel header="Cadastro de Tipos de Instituições">
							<p:panelGrid columns="2" styleClass="semBorda">
								<p:outputLabel value="Nome do Tipo de Instituição">
									<p:outputLabel value="*" style="font-size:11px; color:red;" />
									<h:graphicImage library="lavor" name="ajuda.png" height="15"
										width="15" style="float:right;" onclick="PF('dlg1').show();" />
								</p:outputLabel>
								<p:inputText size="100" required="true"
									value="#{cadastroTipoInstituicaoBean.tipoInstituicao.descricaoTipoInstituicao}"
									label="Nome do Tipo de Instituição" immediate="true"
									maxlength="100"
									placeholder="informe o nome do Tipo de Instituição"
									title="Informe o nome do Tipo de Instituição." />

								<p:outputLabel />
								<p:outputLabel value=" * é campo de preenchimento obrigatório"
									style="font-size:11px; color:red;" />
								<p:commandButton value="Salvar"
									action="#{cadastroTipoInstituicaoBean.editar}"
									icon="ui-icon-save" process="@form" update="@form" style="width:100px"/>
							</p:panelGrid>
						</p:panel>
					</h:form>
					<p:dialog header="Ajuda: Nome do Tipo de Instituição"
						widgetVar="dlg1" showEffect="explode" width="600" height="90"
						resizable="false" maximizable="false" position="center"
						hideEffect="explode">
						<h:outputText
							value="É a descrição do nome do Tipo de uma Instituição(Órgão)." />
						<br />
						<br />
						<h:outputText value="Por exemplo: Administração Direta" />
						<br />
						<div align="center">
							<p:button value="OK" icon="ui-icon-check"
								onclick="PF('dlg1').hide(); return false" style="width:100px" />
						</div>
					</p:dialog>
				</div>
			</div>
		</div>
	</ui:define>
</ui:composition>

src/main/webapp/paginas/TipoInstituicao/ConsultaTiposInstituicoes.xhtml
<!DOCTYPE html>
<ui:composition template="/WEB-INF/template.xhtml"
	xmlns="http://www.w3.org/1999/xhtml"
	xmlns:f="http://xmlns.jcp.org/jsf/core"
	xmlns:h="http://xmlns.jcp.org/jsf/html"
	xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
	xmlns:p="http://primefaces.org/ui">

	<f:metadata>
		<f:viewAction action="#{consultaTiposInstituicoesBean.consultar}" />
	</f:metadata>

	<ui:define name="titulo">Consulta de Tipos de Instituições</ui:define>

	<ui:define name="content">
		<div class="ui-g ui-fluid">
			<div class="ui-g-12">
				<div class="card">
					<h1>
						<h:graphicImage library="lavor" name="tipoinstituicao.png"
							height="45" width="45" />
						Consulta de Tipos de Instituições <a href="../../dashboard.xhtml"><h:graphicImage
								library="lavor" name="voltar.gif" height="35" width="80"
								style="float:right;" /> </a>
					</h1>

					<h:form id="frm">
						<p:messages showDetail="false" showSummary="true"
							autoUpdate="true" />

						<p:dataTable
							value="#{consultaTiposInstituicoesBean.tiposIntituicoes}"
							expandableRowGroups="true" reflow="true" selectionMode="single"
							selection="#{consultaTiposInstituicoesBean.tipoInstituicaoSelecionado}"
							rowKey="#{tipoInstituicao.codigoTipoInstituicao}"
							var="tipoInstituicao" border="1" cellspacing="0" cellpadding="2"
							paginator="true" rowsPerPageTemplate="8,25,50,100" rows="8"
							paginatorPosition="bottom" id="tabela"
							emptyMessage="Não foi localizado o registro solicitado."
							paginatorTemplate="{CurrentPageReport}  {FirstPageLink} {PreviousPageLink} {PageLinks} {NextPageLink} {LastPageLink} {RowsPerPageDropdown}"
							currentPageReportTemplate="Total de {totalRecords} registros localizados - Página: {currentPage} de {totalPages}">

							<f:facet name="header">
       				 Lista de Tipos de Instituição
					<div align="right">
									<p:commandButton id="toggler" type="button"
										value="Ajuste Colunas" icon="ui-icon-calculator" />
								</div>
								<p:columnToggler datasource="tabela" trigger="toggler" />
							</f:facet>

							<f:facet name="footer">
								<div align="right">
									Exportar
									<h:commandLink>
										<h:graphicImage library="lavor" name="pdf.png" width="20"
											title="Exportar para PDF" />
										<p:dataExporter type="pdf" target="tabela"
											fileName="tiposinstituicao" />
									</h:commandLink>

									<h:commandLink>
										<h:graphicImage library="lavor" name="xls.png" width="20"
											title="Exportar para XLS" />
										<p:dataExporter type="xls" target="tabela"
											fileName="tiposinstituicao" />
									</h:commandLink>

									<h:commandLink>
										<h:graphicImage library="lavor" name="xml.png" width="20"
											title="Exportar para XML" />
										<p:dataExporter type="xml" target="tabela"
											fileName="tiposinstituicao" />
									</h:commandLink>
								</div>
							</f:facet>

							<p:column headerText="Nome do Tipo de Instituição"
								style="width:30%"
								sortBy="#{tipoInstituicao.descricaoTipoInstituicao}"
								filterBy="#{tipoInstituicao.descricaoTipoInstituicao}"
								filterMatchMode="contains" id="campomarca">
								<h:outputText
									value="#{tipoInstituicao.descricaoTipoInstituicao}" />
							</p:column>

							<p:column headerText="Ação" style="width:7%" exportable="false">
								<div align="center">
									<p:column style="width:20px">
										<p:commandButton update=":frm:tipoInstituicaoDetalhes" styleClass="blue-grey-btn"
											oncomplete="PF('dlgver').show()" icon="ui-icon-search"
											title="Ver">
											<f:setPropertyActionListener value="#{tipoInstituicao}"
												target="#{consultaTiposInstituicoesBean.tipoInstituicaoSelecionado}" />
										</p:commandButton>
									</p:column>
									<p:column style="width:20px">
										<p:button icon="ui-icon-pencil" title="Alterar"
										    rendered="#{seguranca.autoridades=='[ROLE_ADMINISTRADORES]'}"
											outcome="/paginas/TipoInstituicao/CadastroTipoInstituicaoEdit">
											<f:param name="codigoTipoInstituicao"
												value="#{tipoInstituicao.codigoTipoInstituicao}" />
										</p:button>
									</p:column>
									<p:column style="width:20px">
										<p:commandButton icon="ui-icon-trash" title="Excluir" styleClass="red-btn"
										    rendered="#{seguranca.autoridades=='[ROLE_ADMINISTRADORES]'}"
											process="@this" update="@form"
											action="#{consultaTiposInstituicoesBean.excluir}">
											<p:confirm header="Excluindo..."
												message="Tem certeza que deseja excluir este Registro?"
												icon="ui-icon-alert" />
											<f:setPropertyActionListener value="#{tipoInstituicao}"
												target="#{consultaTiposInstituicoesBean.tipoInstituicaoSelecionado}" />
										</p:commandButton>
									</p:column>
								</div>
							</p:column>
						</p:dataTable>
						<p:dialog header="Detalhes: Tipo de Instituição"
							widgetVar="dlgver" modal="true" showEffect="fade"
							hideEffect="fade" resizable="false">
							<p:outputPanel id="tipoInstituicaoDetalhes"
								style="text-align:center;">
								<p:panelGrid columns="2"
									rendered="#{not empty consultaTiposInstituicoesBean.tipoInstituicaoSelecionado}"
									columnClasses="label,value">

									<h:outputText value="Código Interno" style="font-weight:bold" />
									<h:outputText
										value="#{consultaTiposInstituicoesBean.tipoInstituicaoSelecionado.codigoTipoInstituicao}"
										style="font-weight:bold" />

									<h:outputText value="Nome do Tipo de Instituição"
										style="font-weight:bold" />
									<h:outputText
										value="#{consultaTiposInstituicoesBean.tipoInstituicaoSelecionado.descricaoTipoInstituicao}"
										style="font-weight:bold" />
								</p:panelGrid>
							</p:outputPanel>
							<br />
							<div align="center">
								<p:button value="OK" icon="ui-icon-check"
									onclick="PF('dlgver').hide(); return false" style="width:100px"/>
							</div>
						</p:dialog>
					</h:form>
				</div>
			</div>
		</div>
	</ui:define>
</ui:composition>